# Generated by Django 4.2.16 on 2024-12-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='asignado_a',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
